"""initial schema

Revision ID: 16ef7db229cf
Revises: 
Create Date: 2026-07-26 19:51:16.409820
"""
from alembic import op
import sqlalchemy as sa


revision = '16ef7db229cf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_email', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource', sa.String(length=128), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hospitals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('region', sa.String(length=128), nullable=False),
    sa.Column('data_size', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('data_seed', sa.Integer(), nullable=False),
    sa.Column('risk_shift', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('training_rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('num_rounds', sa.Integer(), nullable=False),
    sa.Column('local_epochs', sa.Integer(), nullable=False),
    sa.Column('dp_enabled', sa.Boolean(), nullable=False),
    sa.Column('dp_epsilon', sa.Float(), nullable=False),
    sa.Column('secure_aggregation', sa.Boolean(), nullable=False),
    sa.Column('hospital_ids', sa.JSON(), nullable=False),
    sa.Column('current_round', sa.Integer(), nullable=False),
    sa.Column('global_accuracy', sa.Float(), nullable=True),
    sa.Column('global_auc', sa.Float(), nullable=True),
    sa.Column('global_loss', sa.Float(), nullable=True),
    sa.Column('history', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('num_samples', sa.Integer(), nullable=False),
    sa.Column('local_loss', sa.Float(), nullable=False),
    sa.Column('local_accuracy', sa.Float(), nullable=False),
    sa.Column('local_auc', sa.Float(), nullable=False),
    sa.Column('update_norm', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['round_id'], ['training_rounds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_updates_hospital_id'), 'client_updates', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_client_updates_round_id'), 'client_updates', ['round_id'], unique=False)
    op.create_table('model_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('auc', sa.Float(), nullable=False),
    sa.Column('loss', sa.Float(), nullable=False),
    sa.Column('num_parameters', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('weights', sa.LargeBinary(), nullable=False),
    sa.Column('scaler', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['round_id'], ['training_rounds.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('model_version_id', sa.Integer(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('diagnosis', sa.String(length=16), nullable=False),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_user_id'), 'predictions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_predictions_user_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_table('model_versions')
    op.drop_index(op.f('ix_client_updates_round_id'), table_name='client_updates')
    op.drop_index(op.f('ix_client_updates_hospital_id'), table_name='client_updates')
    op.drop_table('client_updates')
    op.drop_table('training_rounds')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('hospitals')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
